#!/bin/bash
# author: andreasl

script_name="${0##*/}"
IFS= read -r -d '' script_description << HELP_EOF
${script_name}
Calls \`git status --branch --short --untracked-files\` on each repository in the given reposets and
returns the output in a concise format.

Usage:
  ${script_name} [<reposet>...]

Examples:
  ${script_name}             # call \`git status -bsu\` on the default reposet
  ${script_name} my          # call \`git status -bsu\` on the reposet 'my'
  ${script_name} my work     # call \`git status -bsu\` on the reposets 'my' and 'work'
  ${script_name} -h          # print the usage message
  ${script_name} --help      # print the usage message
HELP_EOF

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=reposet.inc.sh
source "${script_dir}/reposet.inc.sh"

while [ "$#" -gt '0' ]; do
    case "$1" in
    -h|--help)
        printf -- "$script_description"
        exit 0
        ;;
    *) # reposet name / unknown option
        break
        ;;
    esac
    shift
done

load_reposets_or_die "$@"
print_all_repos_status_or_die 1
