#!/bin/bash
#
# Contains the command 'reposet'.
# Dispatches to the given subcommands or prints the help-message.
#
# author: andreasl

script_name="${0##*/}"
IFS= read -r -d '' script_description << HELP_EOF
${script_name}
A flexible and simple command to deal with sets of git repositories.

Reposet provides a handful of subcommands to run common or specified actions on sets of git
repositories.

Commands are:

  ${script_name} apply      - execute a given bash command or series of commands
  ${script_name} list       - list contents of given reposets
  ${script_name} list-sets  - list reposets
  ${script_name} pull       - pull from a remote
  ${script_name} push       - push to a remote
  ${script_name} status     - show status of repositories
  ${script_name} sync       - combined pull and push

Usage:
  ${script_name} [<subcommand>] [...]

Examples:
  ${script_name}                       # print the status of the repositories in the default reposet
  ${script_name} pull work             # call git pull --rebase on all repos in the reposet \"work\"
  ${script_name} push my work          # call git push on all repos in the reposets \"my\" and \"work\"
  ${script_name} apply -q my -- ls -al # call \`ls -al\` on each repository in the reposet \"my\"
  ${script_name} -h                    # print the usage message
  ${script_name} --help                # print the usage message

For more information visit http://github.com/langenhagen/reposet.
HELP_EOF

function show_version {
    printf 'reposet version %s\n' '0.8.7'
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ "$#" -gt '0' ] ; then
    subcommand="$1"
    shift
    case "${subcommand}" in
    -h|--help|help)
        printf -- "$script_description"
        ;;
    -v|--version|version)
        show_version
        ;;
    apply)
        bash "${script_dir}/reposet-apply" "$@"
        ;;
    list-sets|sets)
        bash "${script_dir}/reposet-list-sets" "$@"
        ;;
    list|ls)
        bash "${script_dir}/reposet-list" "$@"
        ;;
    pull|down)
        bash "${script_dir}/reposet-pull" "$@"
        ;;
    push|up)
        bash "${script_dir}/reposet-push" "$@"
        ;;
    status)
        bash "${script_dir}/reposet-status" "$@"
        ;;
    sync)
        bash "${script_dir}/reposet-sync" "$@"
        ;;
    *) # unknown option
        first_reposet="$subcommand"
        bash "${script_dir}/reposet-status" "$first_reposet" "$@"
        ;;
    esac
else
    bash "${script_dir}/reposet-status"
fi

exit "$?"
