#!/bin/bash
# author: andreasl

script_name="${0##*/}"
IFS= read -r -d '' script_description << HELP_EOF
${script_name}
Lists all available reposets names, i.e. the filenames of the *.reposet files without the suffix.
The nameless default reposet \".reposet\" is represented as \"(default)\", when available.

Usage:
  ${script_name}

Example:
  ${script_name}             # list the reposet names
  ${script_name} -h          # print the usage message
  ${script_name} --help      # print the usage message
HELP_EOF

while [ "$#" -gt '0' ]; do
    case "$1" in
    -h|--help)
        printf -- "$script_description"
        exit 0
        ;;
    *) # unknown option
        break
        ;;
    esac
    shift
done

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=reposet.inc.sh
source "${script_dir}/reposet.inc.sh"

if ! cd "$reposets_dir" 2>/dev/null; then
    die "Could not cd into \"${reposets_dir}\". Do you have a reposets folder?" 1
fi

[ -f "${reposets_dir}/.reposet" ] && printf '(default)\n'
for file in *.reposet; do
    printf '%s\n' "${file%.reposet}"
done
